services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    networks:
      - default

  bbus-be:
    depends_on:
      - postgres
    container_name: bbus-be
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default:
    name: bbus-be

volumes:
#  mysql_data:
  postgres:





