spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres #for build docker
#    url: jdbc:postgresql://localhost:5432/postgres #for running test
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  sendGrid:
    apiKey: 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
    fromEmail: bbussystem.v1@gmail.com
    templateId: d-1f92ab7c606c4875a6a98d950e9d0399
    verificationLink: http://localhost:8080/user/confirm-email

# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: bbus-be
    server: http://localhost:${server.port}
    title: Backend for bbus
    version: 1.0.0

# Generate HMAC Authentication Code: https://www.devglan.com/online-tools/hmac-sha256-online
jwt:
  expiryMinutes: 60
  expiryDay: 14
  accessKey: 0n7DdBQLmxxWo+3yIuTGfMvEr1ZVhqM7lI9jzCfN1Ps=
  refreshKey: XGTgA+M/suH/HcW/a6B6Dc78VxCGHDPGbsOXPZUfWE0=
#  secretKey: EnricVan



mqtt:
  # MQTT Broker Configuration
  broker-url: tcp://3.1.102.2:1883
  username: admin
  password: admin
  client-id: springBootClient
  clean-session: true
  # Optional properties
  connection-timeout: 10
  keep-alive: 60
  # Request and Response Topics
  topic: '#'