spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres #for build docker
#    url: jdbc:postgresql://localhost:5432/postgres #for running test
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  sendGrid:
    apiKey: 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
    fromEmail: bbussystem.v1@gmail.com

# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: bbus-be
    server: http://localhost:${server.port}
    title: Backend for bbus
    version: 1.0.0

jwt:
  secretKey: abc@123

